# Generated by Django 2.0.1 on 2018-04-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='Vaildated',
            new_name='Validated',
        ),
    ]
