# Generated by Django 2.0.1 on 2018-04-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0002_auto_20180429_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='Validated',
            new_name='Validated_time',
        ),
    ]
