# Generated by Django 2.0.1 on 2018-05-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0003_auto_20180429_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100, verbose_name='请求IP地址')),
                ('req_count', models.IntegerField(default=0, verbose_name='总请求次数')),
                ('limit_count', models.IntegerField(default=0, verbose_name='限制请求次数')),
                ('limit', models.CharField(choices=[('T', '限制'), ('F', '不限制')], default='F', max_length=10, verbose_name='限制访问')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
